package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/GestionNotificaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from snotificaciones.idl
* jueves 18 de junio de 2020 04:55:09 PM COT
*/

public interface GestionNotificaciones extends GestionNotificacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionNotificaciones
