package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/GestionNotificacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from snotificaciones.idl
* jueves 18 de junio de 2020 04:55:09 PM COT
*/

public interface GestionNotificacionesOperations 
{
  void notificarMensaje (servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO objNotificacion);
} // interface GestionNotificacionesOperations
