package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/GestionAsintomaticosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from salertas.idl
* jueves 18 de junio de 2020 04:55:18 PM COT
*/

public interface GestionAsintomaticosOperations 
{
  void registrarAsintomatico (servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTO objDTO, org.omg.CORBA.BooleanHolder resultado);
  boolean enviarIndicador (int id, float ToC);
} // interface GestionAsintomaticosOperations
