package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/GestionAsintomaticosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from salertas.idl
* jueves 18 de junio de 2020 04:55:18 PM COT
*/

public abstract class GestionAsintomaticosPOA extends org.omg.PortableServer.Servant
 implements servidorAlertas.sop_corba.GestionAsintomaticosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registrarAsintomatico", new java.lang.Integer (0));
    _methods.put ("enviarIndicador", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // servidorAlertas/sop_corba/GestionAsintomaticos/registrarAsintomatico
       {
         servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTO objDTO = servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTOHelper.read (in);
         org.omg.CORBA.BooleanHolder resultado = new org.omg.CORBA.BooleanHolder ();
         this.registrarAsintomatico (objDTO, resultado);
         out = $rh.createReply();
         out.write_boolean (resultado.value);
         break;
       }

       case 1:  // servidorAlertas/sop_corba/GestionAsintomaticos/enviarIndicador
       {
         int id = in.read_long ();
         float ToC = in.read_float ();
         boolean $result = false;
         $result = this.enviarIndicador (id, ToC);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:servidorAlertas/sop_corba/GestionAsintomaticos:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionAsintomaticos _this() 
  {
    return GestionAsintomaticosHelper.narrow(
    super._this_object());
  }

  public GestionAsintomaticos _this(org.omg.CORBA.ORB orb) 
  {
    return GestionAsintomaticosHelper.narrow(
    super._this_object(orb));
  }


} // class GestionAsintomaticosPOA
