package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/GestionAsintomaticosPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from salertas.idl
* jueves 18 de junio de 2020 04:55:18 PM COT
*/

public class GestionAsintomaticosPOATie extends GestionAsintomaticosPOA
{

  // Constructors

  public GestionAsintomaticosPOATie ( servidorAlertas.sop_corba.GestionAsintomaticosOperations delegate ) {
      this._impl = delegate;
  }
  public GestionAsintomaticosPOATie ( servidorAlertas.sop_corba.GestionAsintomaticosOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public servidorAlertas.sop_corba.GestionAsintomaticosOperations _delegate() {
      return this._impl;
  }
  public void _delegate (servidorAlertas.sop_corba.GestionAsintomaticosOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void registrarAsintomatico (servidorAlertas.sop_corba.GestionAsintomaticosPackage.asintomaticoDTO objDTO, org.omg.CORBA.BooleanHolder resultado)
  {
    _impl.registrarAsintomatico(objDTO, resultado);
  } // registrarAsintomatico

  public boolean enviarIndicador (int id, float ToC)
  {
    return _impl.enviarIndicador(id, ToC);
  } // enviarIndicador

  private servidorAlertas.sop_corba.GestionAsintomaticosOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class GestionAsintomaticosPOATie
