package servidorNotificaciones.sop_corba.GestionNotificacionesPackage;


/**
* servidorNotificaciones/sop_corba/GestionNotificacionesPackage/ClsMensajeNotificacionDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from snotificaciones.idl
* jueves 18 de junio de 2020 04:55:09 PM COT
*/

abstract public class ClsMensajeNotificacionDTOHelper
{
  private static String  _id = "IDL:servidorNotificaciones/sop_corba/GestionNotificaciones/ClsMensajeNotificacionDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "tipo_id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[2] = new org.omg.CORBA.StructMember (
            "ToC",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTOHelper.id (), "ClsMensajeNotificacionDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO value = new servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO ();
    value.tipo_id = istream.read_string ();
    value.id = istream.read_long ();
    value.ToC = istream.read_float ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, servidorNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO value)
  {
    ostream.write_string (value.tipo_id);
    ostream.write_long (value.id);
    ostream.write_float (value.ToC);
  }

}
