package servidorNotificaciones.sop_corba.GestionNotificacionesPackage;


/**
* servidorNotificaciones/sop_corba/GestionNotificacionesPackage/ClsMensajeNotificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from snotificaciones.idl
* jueves 18 de junio de 2020 04:55:09 PM COT
*/

public final class ClsMensajeNotificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String tipo_id = null;
  public int id = (int)0;
  public float ToC = (float)0;

  public ClsMensajeNotificacionDTO ()
  {
  } // ctor

  public ClsMensajeNotificacionDTO (String _tipo_id, int _id, float _ToC)
  {
    tipo_id = _tipo_id;
    id = _id;
    ToC = _ToC;
  } // ctor

} // class ClsMensajeNotificacionDTO
